%% This script uses three files to generate a features summary table from Hydra data.

% 1. Compiled Hydra metadata file; 2. Filenames file generated by Tierpsy; 3. Features summary file generated by Tierpsy.
% author: serenading. Jan 2021

clear 
close all

%% Import features data and combine with metadata

% set which feature extraction timestamp to use
extractStamp = '20210112_105808'; % 20201218_184325 for standard feature extraction, 20210112_105808 for filtered data

% load features matrix, correspondong filenames, and metadata
tierpsyFeatureTable = readtable(['/Users/sding/OneDrive - Imperial College London/species/features_summary_tierpsy_plate_' extractStamp '.csv'],'Delimiter',',');%,'preserveVariableNames',true);
tierpsyFileTable = readtable(['/Users/sding/OneDrive - Imperial College London/species/filenames_summary_tierpsy_plate_' extractStamp '.csv'],'Delimiter',',','CommentStyle','#');%,'preserveVariableNames',true);
metadataTable = readtable('/Users/sding/OneDrive - Imperial College London/species/wells_updated_metadata.csv','Delimiter',',','preserveVariableNames',true);

% rename metadata column heads to match Tierpsy output
metadataTable.Properties.VariableNames{'imgstore_name'} = 'filename';
metadataTable.Properties.VariableNames{'worm_strain'} = 'strain_name';

% reformat the filenames to match the imgstore name
filenames = tierpsyFileTable.filename;
splitnames = cellfun(@(x) strsplit(x,'/'), filenames,'UniformOutput', false);
reconstructnames = cellfun(@(x) strcat(x{6},'/',x{7}), splitnames,'UniformOutput',false);
tierpsyFileTable.filename = reconstructnames;

%% Join tables

% join the Tierpsy tables to match filenames with file_id. Required in case
% features were not extracted for any files.
combinedTierpsyTable = outerjoin(tierpsyFileTable,tierpsyFeatureTable,'MergeKeys',true);

% finally, join tables to get strain names for each set of features
featureTable = outerjoin(metadataTable,combinedTierpsyTable,'MergeKeys',true);

% get row logical index for valid files
% (note: this does not give a balanced set of files where good data for all three light conditions are present)
rowLogInd_wellAnnotator = strcmp(featureTable.is_bad_well,'False') & featureTable.well_label==1;
rowLogInd_Tierpsy = strcmp(featureTable.is_good,'True') & featureTable.is_good_well==1;
rowLogInd = rowLogInd_wellAnnotator & rowLogInd_Tierpsy; % ~75% data is good

% trim featureTable down to those with valid files
featureTable = featureTable(rowLogInd,:);

% export full features table
writetable(featureTable,['/Users/sding/OneDrive - Imperial College London/species/Results/fullFeaturesTable_' extractStamp '.csv']);